# Generated by Django 5.2.9 on 2026-06-26 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchEval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_score', models.IntegerField()),
                ('accuracy_reason', models.TextField()),
                ('completeness_score', models.IntegerField()),
                ('completeness_reason', models.TextField()),
                ('clarity_score', models.IntegerField()),
                ('clarity_reason', models.TextField()),
                ('source_quality_score', models.IntegerField()),
                ('source_quality_reason', models.TextField()),
                ('overall_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eval', to='agent.researchsession')),
            ],
        ),
    ]
